[package]
name = "zellij-supabar"
version = "0.1.0"
authors = ["Oliver Sargison <sargo@sargo.cc>"]
edition = "2018"

[dependencies]
ansi_term = "0.12.1"
zellij-tile = "0.37.2"
chrono = "0.4.0"
owo-colors = "3.5.0"
git_info = "0.1.2"
